[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask==3.0.0",
    "flask-cors==4.0.0",
    "gunicorn==21.2.0",
    "requests==2.31.0",
    "werkzeug==3.0.1",
    "yt-dlp==2025.1.26",
]
